# -*- coding: utf-8 -*-
"""P2HW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FxcDob2I8YLlnGtXXJVCDyNAmAMqQMZ
"""

#Jerico Branch
#2/25/2025
#P2HW1
#Formatting The Display of the output


#Get User Input
first_num = float(input("Enter Budget: "))
travel_dest = input("Enter the travel destination: ")
gas_price = float(input("How much do you think you will spend on gas? "))
accommodation_price = float(input("How much do you think you will spend on accommodation/hotel? "))
food_price = float(input("Last, how much do you think you will spend on food? "))

#Calculate the remaining balance

remaining_balance = first_num - (gas_price + accommodation_price + food_price)

#Output the data
print("-"*9 + " Travel Expenses " + "-"*9)

print(f"{'Destination:':<20} {travel_dest}")
print(f"{'Initial Budget:':<20} ${first_num:,.2f}")
print(f"{'Fuel:':<20} ${gas_price:,.2f}")
print(f"{'accommodation:':<20} ${accommodation_price:,.2f}")
print(f"{'Food:':<20} ${food_price:,.2f}")
print("-" * 35)
print(f"{'Remaining Balance:':<20} ${remaining_balance:,.2f}")