# -*- coding: utf-8 -*-
"""P3HW_Debugged

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzIchSv9fXYcd8f8Xep4bzspoTX50H3h
"""

#Jerico Branch
#3/13/2025
#P3HW1

# This program takes a number grade , determines average and displays letter grade for average.

# Enter grades for six modules

mod_1 = float(input('Enter grade for Module 1: '))
mod_2 = float(input('Enter grade for Module 2: '))
mod_3 = float(input('Enter grade for Module 3: '))
mod_4 = float(input('Enter grade for Module 4: '))
mod_5 = float(input('Enter grade for Module 5: '))
mod_6 = float(input('Enter grade for Module 6: '))

# add grades entered to a list

grades = [mod_1, mod_2, mod_3, mod_4, mod_5, mod_6]
# TO DO: determine lowest, highest , sum and average for grades
# Calculate required values
# Use 'grades' instead of 'module_grades'
lowest_grade = min(grades)
highest_grade = max(grades)
sum_of_grades = sum(grades)
average_grade = sum_of_grades / len(grades)

# Display the results in the required format

print("-"*9 + " Results " + "-"*9)

print(f"{'Lowest Grade:':<20} {lowest_grade}")
print(f"{'Highest Grade:':<20} {highest_grade}")
print(f"{'Sum of Grades:':<20} {sum_of_grades}")
print(f"{'Average Grade:':<20} {average_grade:.2f}")
print("-" * 30)


# determine letter grade for average

print("--" * 20)
# Assign the calculated average to 'avg'
avg = average_grade
print(f"Average: {avg:.2f}")
print("--" * 20)

if avg >= 90:
    print('Your grade is: A')
elif avg >= 80:
    print('Your grade is: B')
elif avg >= 70:
    print('Your grade is: C')
elif avg >= 60:
    print('Your grade is: D')
else:
    print('Your grade is: F')